export enum ChatActionType {
	SEND_MESSAGE = 'SEND_MESSAGE',
	CLEAR_CHAT = 'CLEAR_CHAT',
	DELETE_CONTACT = 'DELETE_CONTACT'
}

export enum MESSAGE_DIRECTION {
	INCOMING = 'INCOMING',
	OUTGOING = 'OUTGOING',
	SYSTEM = 'SYSTEM'
}
